### ISSUE TITLE
ECE much lower than reported

### ISSUE THREAD

**Issue by kheuton** [omegafragger/DDU#1]
Thanks for the great repo! I've been curious about DDU so I've been playing around with some examples. I fit a wide resnet to CIFAR-10 with spectral normalization, and while I got a reasonable test accuracy (0.9587), my ECE is much lower than the values reported in the DDU paper.

I see test ECE's of 0.023 on CIFAR-10, but the paper reports ECE's nearly 2 orders of magnitude higher, of 0.85.
Does the ECE method in this repository report a metric that is somehow different than the metric used in the DDU paper?

Should the ece reported by the `expected_calibration_error` method be multiplied by 100, so my test ECE is actually 2.3 and higher than expected?

I believe I am using all the same hyperparameters:
```
batch_size=128
val_size = 0.1
spec_norm = True
coeff = 3
mod = True

lr = 0.1
momentum = 0.9
weight_decay = 5e-4

epochs = 350
milestone_1 = 150
milestone_2 = 250

**Comment by kheuton** [comment]
Whoops, just re-read the paper and saw that ECE is reported after temperature scaling. My numbers match  up after temperature scaling. Sorry for the noise

**Comment by Hugo101** [comment]
@kheuton  Hi Kheuton,

I am running the same experiment, and get the two ECEs as below:
- before temperature scaling: 0.0244, multiplying by 100 -> 2.44 
- after temperature scaling: 0.0100, multiplying by 100 -> 1.00

The reported ECE is 0.85 in Table 1. So I am wondering whether you replicated some results close to 0.85 or close to 1.00?

Hi @omegafragger  ,

We should not view 0.85 and 1.00 are close right? Could you please give some hints how to reproduce ECE on Table 1? I used the exactly the same parameters in your provided code.
The only difference is that:
I only run 1 run, and the paper mentioned that the results are averaged from 25 runs.

But considering the std is also small, so I prefer I might make some minor mistakes.

Thank you!
Best,
Hugo
